In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel(r"C:\Users\nmark\Code\BA_Forage\ba-forage-data-science\data\flight_data.xlsx")
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FLIGHT_DATE           10000 non-null  datetime64[us]
 1   FLIGHT_TIME           10000 non-null  object
 2   TIME_OF_DAY           10000 non-null  str
 3   AIRLINE_CD            10000 non-null  str
 4   FLIGHT_NO             10000 non-null  str
 5   DEPARTURE_STATION_CD  10000 non-null  str
 6   ARRIVAL_STATION_CD    10000 non-null  str
 7   ARRIVAL_COUNTRY       10000 non-null  str
 8   ARRIVAL_REGION        10000 non-null  str
 9   HAUL                  10000 non-null  str
 10  AIRCRAFT_TYPE         10000 non-null  str
 11  FIRST_CLASS_SEATS     10000 non-null  int64
 12  BUSINESS_CLASS_SEATS  10000 non-null  int64
 13  ECONOMY_SEATS         10000 non-null  int64
 14  TIER1_ELIGIBLE_PAX    10000 non-null  int64
 15  TIER2_ELIGIBLE_PAX    10000 non-null  int64
 16  TIER3_ELIGIBLE_PAX    10000 non-null  int64
dtypes: datetime64[us](1), int64(6), object(1), str(9)
memory usage: 1.3+ MB

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27

In [12]:
tier_cols = ["TIER1_ELIGIBLE_PAX", "TIER2_ELIGIBLE_PAX", "TIER3_ELIGIBLE_PAX"]
total_pax = df["FIRST_CLASS_SEATS"] + df["BUSINESS_CLASS_SEATS"] + df["ECONOMY_SEATS"]

eligible_sum = df.groupby(["HAUL", "TIME_OF_DAY"])[tier_cols].sum()
total_sum = total_pax.groupby([df["HAUL"], df["TIME_OF_DAY"]]).sum()

summary = eligible_sum.div(total_sum, axis=0) * 100
summary.columns = ["TIER1_PCT", "TIER2_PCT", "TIER3_PCT"]
summary.reset_index()

    HAUL TIME_OF_DAY  TIER1_PCT  TIER2_PCT  TIER3_PCT
0   LONG   Afternoon   0.198372   2.765564  10.521373
1   LONG     Evening   0.212001   2.674498  10.264195
2   LONG   Lunchtime   0.176841   2.710504  10.383658
3   LONG     Morning   0.205362   2.789037  10.632896
4  SHORT   Afternoon   0.341630   4.313486  16.587360
5  SHORT     Evening   0.328410   4.451611  16.995700
6  SHORT   Lunchtime   0.394100   4.548657  17.275062
7  SHORT     Morning   0.339939   4.357983  16.742925