In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("data/flight_data.xlsx")
df

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025-06-07,22:04:00,Evening,BA,BA7039,LHR,VIE,Austria,Europe,SHORT,A320,0,7,173,1,15,51
9996,2025-04-22,15:15:00,Afternoon,BA,BA9712,LHR,ORD,USA,North America,LONG,B777,8,49,178,1,0,0
9997,2025-08-16,06:11:00,Morning,BA,BA7513,LHR,HND,Japan,Asia,LONG,B777,0,32,304,0,4,19
9998,2025-10-24,22:02:00,Evening,BA,BA9958,LHR,DXB,UAE,Middle East,LONG,B787,8,48,200,1,10,38
9999,2025-05-28,22:00:00,Evening,BA,BA8374,LHR,DFW,USA,North America,LONG,B787,0,35,179,2,11,40

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FLIGHT_DATE           10000 non-null  datetime64[us]
 1   FLIGHT_TIME           10000 non-null  object
 2   TIME_OF_DAY           10000 non-null  str
 3   AIRLINE_CD            10000 non-null  str
 4   FLIGHT_NO             10000 non-null  str
 5   DEPARTURE_STATION_CD  10000 non-null  str
 6   ARRIVAL_STATION_CD    10000 non-null  str
 7   ARRIVAL_COUNTRY       10000 non-null  str
 8   ARRIVAL_REGION        10000 non-null  str
 9   HAUL                  10000 non-null  str
 10  AIRCRAFT_TYPE         10000 non-null  str
 11  FIRST_CLASS_SEATS     10000 non-null  int64
 12  BUSINESS_CLASS_SEATS  10000 non-null  int64
 13  ECONOMY_SEATS         10000 non-null  int64
 14  TIER1_ELIGIBLE_PAX    10000 non-null  int64
 15  TIER2_ELIGIBLE_PAX    10000 non-null  int64
 16  TIER3_ELIGIBLE_PAX    10000 non-null  int64
dtypes: datetime64[us](1), int64(6), object(1), str(9)
memory usage: 1.3+ MB

In [7]:
df.describe()

,FLIGHT_DATE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
count,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2025-07-14 07:04:04.800000,1.547200,25.073800,198.385900,0.607700,7.951900,30.421400
min,2025-04-01 00:00:00,0.000000,0.000000,160.000000,0.000000,0.000000,0.000000
25%,2025-05-22 00:00:00,0.000000,8.000000,167.000000,0.000000,4.000000,20.000000
50%,2025-07-13 00:00:00,0.000000,17.000000,175.000000,0.000000,8.000000,30.000000
75%,2025-09-06 00:00:00,0.000000,35.000000,180.000000,1.000000,11.000000,41.000000
max,2025-10-30 00:00:00,14.000000,97.000000,358.000000,20.000000,29.000000,92.000000
std,NaN,3.625395,22.142348,53.653478,1.006232,5.130752,15.284233